"""Single source of truth. Official entry URLs are not promises of native RSS."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# category, vendor, family, aliases, official entry. One vendor can own many families.
ROWS = [
('phone','华为','Huawei','华为|HUAWEI|Mate|Pura|nova','https://consumer.huawei.com/cn/press/'),
('phone','荣耀','HONOR','荣耀|Honor|Magic','https://www.honor.com/cn/'),
('phone','小米','Xiaomi','小米|Xiaomi','https://www.mi.com/global/discover/news/'),
('phone','小米','REDMI','红米|Redmi','https://www.mi.com/'),
('phone','小米','POCO','POCO','https://www.mi.com/global/'),
('phone','OPPO','OPPO','OPPO|Find|Reno','https://www.oppo.com/en/newsroom/'),
('phone','OPPO','OnePlus','一加|OnePlus','https://www.oneplus.com/global/press'),
('phone','realme','realme','真我|realme','https://www.realme.com/global/newsroom'),
('phone','vivo','vivo','vivo','https://www.vivo.com/en/about-vivo/news'),
('phone','vivo','iQOO','iQOO','https://www.iqoo.com/cn/'),
('phone','中兴','ZTE','中兴|ZTE|Axon','https://www.ztedevices.com/en/news/'),
('phone','努比亚','nubia','努比亚|nubia','https://www.nubia.com/'),
('phone','努比亚','REDMAGIC','红魔|REDMAGIC|Red Magic','https://global.redmagic.gg/blogs/news'),
('phone','魅族','Meizu','魅族|Meizu','https://www.meizu.com/'),
('phone','Apple','iPhone','苹果|Apple|iPhone','https://www.apple.com/newsroom/'),
('phone','Samsung','Galaxy','三星|Samsung|Galaxy','https://news.samsung.com/global/'),
('phone','Google','Pixel','谷歌|Google|Pixel','https://blog.google/products/devices/pixel/'),
('phone','联想','Motorola','摩托罗拉|Motorola|moto','https://motorolanews.com/'),
('phone','Nothing','Nothing Phone','Nothing|Nothing Phone','https://nothing.tech/blogs/news'),
('phone','Nothing','CMF','CMF','https://cmf.tech/'),
('phone','传音','TECNO','TECNO|传音','https://www.tecno-mobile.com/news/'),
('phone','传音','Infinix','Infinix','https://www.infinixmobility.com/'),
('phone','传音','itel','itel','https://www.itel-life.com/'),
('phone','Sony','Xperia','索尼|Sony|Xperia','https://www.sony.com/en/SonyInfo/News/Press/'),
('phone','SHARP','AQUOS','夏普|SHARP|AQUOS','https://global.sharp/corporate/news/'),
('phone','ASUS','Zenfone / ROG Phone','华硕|ASUS|Zenfone|ROG Phone','https://press.asus.com/'),
('phone','HMD','HMD','HMD','https://www.hmd.com/en_int/press'),
('phone','Fairphone','Fairphone','Fairphone','https://www.fairphone.com/en/'),
('phone','Lava','Lava','Lava|Agni','https://www.lavamobiles.com/'),
('phone','Ulefone','Ulefone','Ulefone|Armor','https://www.ulefone.com/'),
('phone','DOOGEE','DOOGEE','DOOGEE','https://www.doogee.cc/'),
('phone','Blackview','Blackview','Blackview','https://www.blackview.hk/'),
('phone','OUKITEL','OUKITEL','OUKITEL','https://oukitel.com/'),
('phone','Unihertz','Unihertz','Unihertz|Jelly|Titan','https://www.unihertz.com/'),
('phone','AGM','AGM','AGM','https://www.agmmobile.com/'),
('phone','8849','8849','8849|Tank','https://8849tech.com/'),
('ai','DeepSeek','DeepSeek','深度求索|DeepSeek','https://api-docs.deepseek.com/news/'),
('ai','阿里巴巴','Qwen / Wan','通义千问|Qwen|通义万相|Wan','https://qwen.ai/blog'),
('ai','字节跳动','Seed / Doubao','豆包|Doubao|Seed|Seedance|Seedream','https://seed.bytedance.com/en/'),
('ai','腾讯','Hunyuan','混元|Hunyuan','https://hunyuan.tencent.com/'),
('ai','百度','ERNIE','文心|ERNIE','https://yiyan.baidu.com/'),
('ai','智谱 / Z.ai','GLM / CogView / CogVideo','智谱|Z.ai|GLM|CogView|CogVideo','https://z.ai/blog'),
('ai','月之暗面','Kimi','月之暗面|Moonshot|Kimi','https://www.kimi.com/'),
('ai','MiniMax','MiniMax / Hailuo','MiniMax|海螺|Hailuo','https://www.minimax.io/news'),
('ai','阶跃星辰','Step','阶跃星辰|StepFun|Step','https://www.stepfun.com/'),
('ai','科大讯飞','Spark','讯飞星火|Spark','https://xinghuo.xfyun.cn/'),
('ai','商汤','SenseNova','日日新|SenseNova|SenseTime','https://www.sensetime.com/en/news'),
('ai','华为','Pangu','盘古|Pangu','https://www.huaweicloud.com/product/pangu.html'),
('ai','快手','Kling','可灵|Kling','https://klingai.com/'),
('ai','生数科技','Vidu','Vidu|生数','https://www.vidu.com/'),
('ai','爱诗科技','PixVerse','PixVerse|拍我','https://pixverse.ai/'),
('ai','昆仑万维','Skywork','天工|Skywork','https://skywork.ai/'),
('ai','百川智能','Baichuan','百川|Baichuan','https://www.baichuan-ai.com/'),
('ai','零一万物','Yi','零一万物|01.AI|Yi','https://www.01.ai/'),
('ai','面壁智能','MiniCPM','面壁|MiniCPM','https://github.com/OpenBMB'),
('ai','Jina AI','Embeddings / Reranker','Jina|Jina Embeddings|Jina Reranker','https://jina.ai/news/'),
('ai','上海人工智能实验室（研究机构）','InternLM / InternVL','书生|InternLM|InternVL','https://www.shlab.org.cn/'),
('ai','北京智源人工智能研究院（研究机构）','BGE / Emu','智源|BAAI|BGE|Emu','https://www.baai.ac.cn/'),
('ai','OpenAI','GPT / o-series / gpt-oss / Sora','OpenAI|GPT|o1|o3|o4|gpt-oss|Sora','https://openai.com/news/'),
('ai','Anthropic','Claude','Anthropic|Claude|Opus|Sonnet|Haiku','https://www.anthropic.com/news'),
('ai','Google DeepMind','Gemini / Gemma / Imagen / Veo / Lyria','Gemini|Gemma|Imagen|Veo|Lyria','https://deepmind.google/blog/'),
('ai','Meta','Llama','Meta|Llama','https://ai.meta.com/blog/'),
('ai','xAI','Grok','xAI|Grok','https://x.ai/news'),
('ai','Mistral AI','Mistral / Codestral / Devstral / Voxtral','Mistral|Ministral|Codestral|Devstral|Voxtral','https://mistral.ai/news'),
('ai','Cohere','Command / Aya / Embed / Rerank','Cohere|Command|Aya|Embed|Rerank','https://cohere.com/blog'),
('ai','AI21 Labs','Jamba','AI21|Jamba','https://www.ai21.com/blog/'),
('ai','Amazon / AWS','Nova / Titan','Amazon Nova|Amazon Titan|Nova|Titan','https://aws.amazon.com/blogs/aws/'),
('ai','Microsoft','Phi / MAI','Microsoft|Phi|MAI','https://www.microsoft.com/en-us/research/blog/'),
('ai','NVIDIA','Nemotron / Cosmos','NVIDIA|Nemotron|Cosmos','https://blogs.nvidia.com/'),
('ai','IBM','Granite','IBM|Granite','https://research.ibm.com/blog'),
('ai','Apple','OpenELM / 公开模型','Apple|OpenELM','https://machinelearning.apple.com/'),
('ai','Ai2（研究机构）','OLMo / Molmo / Tülu','Ai2|Allen Institute|OLMo|Molmo|Tulu|Tülu','https://allenai.org/blog'),
('ai','TII（研究机构）','Falcon','TII|Falcon','https://www.tii.ae/'),
('ai','Liquid AI','LFM','Liquid AI|LFM','https://www.liquid.ai/blog'),
('ai','Arcee AI','Arcee','Arcee','https://www.arcee.ai/blog'),
('ai','Naver','HyperCLOVA','Naver|HyperCLOVA','https://navercorp.com/'),
('ai','LG AI Research','EXAONE','LG AI Research|EXAONE','https://www.lgresearch.ai/'),
('ai','Upstage','Solar','Upstage|Solar','https://www.upstage.ai/blog'),
('ai','Black Forest Labs','FLUX','Black Forest Labs|BFL|FLUX','https://bfl.ai/announcements'),
('ai','Stability AI','Stable Diffusion','Stability AI|Stable Diffusion|Stable Audio','https://stability.ai/news'),
('ai','Midjourney','Midjourney','Midjourney','https://updates.midjourney.com/'),
('ai','Ideogram','Ideogram','Ideogram','https://about.ideogram.ai/blog'),
('ai','Recraft','Recraft','Recraft','https://www.recraft.ai/blog'),
('ai','Adobe','Firefly','Adobe|Firefly','https://blog.adobe.com/'),
('ai','Runway','Gen / Runway','Runway|Gen-3|Gen-4','https://runwayml.com/research'),
('ai','Luma AI','Ray / Dream Machine','Luma|Ray|Dream Machine','https://lumalabs.ai/'),
('ai','Pika','Pika','Pika','https://pika.art/'),
('ai','ElevenLabs','Eleven / 语音模型','ElevenLabs|Eleven','https://elevenlabs.io/blog'),
('ai','Deepgram','Nova / Aura','Deepgram|Nova|Aura','https://deepgram.com/learn'),
('ai','AssemblyAI','Universal','AssemblyAI|Universal','https://www.assemblyai.com/blog/'),
('ai','Speechmatics','语音模型','Speechmatics','https://www.speechmatics.com/'),
('ai','Cartesia','Sonic','Cartesia|Sonic','https://cartesia.ai/blog'),
('ai','Fish Audio','语音模型','Fish Audio|Fish Speech','https://fish.audio/'),
('ai','Suno','Suno','Suno','https://suno.com/blog'),
('ai','Udio','Udio','Udio','https://www.udio.com/blog'),
]

def make_catalog():
    return [dict(id=f'{category}-{i:03}', category=category, vendor=vendor,
                 family=family, aliases=aliases.split('|'), official_url=url)
            for i,(category,vendor,family,aliases,url) in enumerate(ROWS,1)]

if __name__ == '__main__':
    path=ROOT/'config/catalog.json'
    path.write_text(json.dumps(make_catalog(),ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    print(f'{len(ROWS)} catalog entries written')
